# Generated by Django 4.2.7 on 2026-03-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_patientcompanioncheckin'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcompanioncheckin',
            name='notificado',
            field=models.BooleanField(default=False, verbose_name='Notificado check-out pendente'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='homeservices',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patientcompanioncheckin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='professionalservices',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
