# Generated by Django 4.2.7 on 2026-03-24 21:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_patientcompanioncheckin_notificado_alter_checkin_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcompanioncheckin',
            name='expected_checkout_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data prevista de check-out'),
        ),
    ]
